language: rust
sudo: false
git:
  submodules: false

cache:
  directories:
    - $HOME/.cargo
    - $HOME/.cache
    - $TRAVIS_BUILD_DIR/target

before_cache:
  - find $TRAVIS_BUILD_DIR/target/debug -maxdepth 1 -type f -delete

os:
  - linux
  - osx

rust:
  - stable

before_script:
  - export PATH="$PATH:$HOME/.cache/bin:$HOME/.cargo/bin"
  - GRPC_HEADER="$HOME/.cache/include/grpc/grpc.h"
  - if [[ $TRAVIS_OS_NAME == "osx" ]] && [[ ! -f $GRPC_HEADER ]]; then export CC=clang; brew install autoconf libtool shtool; fi
  - test -f "$GRPC_HEADER" || (git clone --depth 1 -b v1.4.0 https://github.com/grpc/grpc && cd grpc && git submodule update --init && env prefix=$HOME/.cache make install_c)
  - PROTOC_PKG=protoc-3.3.0-${TRAVIS_OS_NAME}-x86_64.zip
  - which protoc || (wget https://github.com/google/protobuf/releases/download/v3.3.0/${PROTOC_PKG} && unzip -u ${PROTOC_PKG} -d $HOME/.cache)
  - export C_INCLUDE_PATH="$HOME/.cache/include"
  - export LD_LIBRARY_PATH="$HOME/.cache/lib"
  - export DYLD_LIBRARY_PATH="$HOME/.cache/lib"
  - export LIBRARY_PATH="$HOME/.cache/lib"
  - export PKG_CONFIG_PATH="$HOME/.cache/lib/pkgconfig"

script:
  - if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then cargo install -f clippy && cargo clippy; fi
  - cargo build --no-default-features
  - cargo build
  - cargo test
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cargo doc --no-deps; fi
  - if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then cargo bench; fi

notifications:
  email:
    on_success: never

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: target/doc/
  on:
    branch: master
    os: osx
