language: rust
cache: cargo

git:
  submodules: false

rust:
  - stable

sudo: false

script:
  - cargo build --no-default-features
  - cargo build
  - cargo test
  - cargo doc --no-deps
  - if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then cargo bench ; fi

notifications:
  email:
    on_success: never

os:
  - osx

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: target/doc/
  on:
    branch: master
