[package]
name = "tf-serving"
version = "0.0.1"
authors = ["Ben Zhang <benzh@cs.berkeley.edu>"]

[dependencies]
bytes           = "0.4.5"
error-chain     = "0.11.0"
flate2          = "0.2"
futures         = "0.1"
futures-cpupool = "0.1"
grpc            = "0.*"
protobuf        = "1.*"
reqwest         = "0.7.3"
ndarray         = "0.10.9"