#!/usr/bin/env bash

ARG="-I=serving -I serving/tensorflow --rust_out=src --grpc_out=src "
ARG+="--plugin=protoc-gen-grpc=`which grpc_rust_plugin` "

protoc $ARG serving/tensorflow/tensorflow/core/example/example.proto
protoc $ARG serving/tensorflow/tensorflow/core/example/feature.proto
protoc $ARG serving/tensorflow/tensorflow/core/framework/attr_value.proto
protoc $ARG serving/tensorflow/tensorflow/core/framework/function.proto
protoc $ARG serving/tensorflow/tensorflow/core/framework/graph.proto
protoc $ARG serving/tensorflow/tensorflow/core/framework/node_def.proto
protoc $ARG serving/tensorflow/tensorflow/core/framework/op_def.proto
protoc $ARG serving/tensorflow/tensorflow/core/framework/resource_handle.proto
protoc $ARG serving/tensorflow/tensorflow/core/framework/tensor.proto
protoc $ARG serving/tensorflow/tensorflow/core/framework/tensor_shape.proto
protoc $ARG serving/tensorflow/tensorflow/core/framework/types.proto
protoc $ARG serving/tensorflow/tensorflow/core/framework/versions.proto
protoc $ARG serving/tensorflow/tensorflow/core/protobuf/meta_graph.proto
protoc $ARG serving/tensorflow/tensorflow/core/protobuf/saver.proto
protoc $ARG serving/tensorflow_serving/apis/classification.proto
protoc $ARG serving/tensorflow_serving/apis/get_model_metadata.proto
protoc $ARG serving/tensorflow_serving/apis/inference.proto
protoc $ARG serving/tensorflow_serving/apis/input.proto
protoc $ARG serving/tensorflow_serving/apis/model.proto
protoc $ARG serving/tensorflow_serving/apis/predict.proto
protoc $ARG serving/tensorflow_serving/apis/prediction_service.proto
protoc $ARG serving/tensorflow_serving/apis/regression.proto
